version: "3.7"
services:
  database:
    image: postgres
    container_name: bookstore_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

  server:
    build: ./
    command: ./bookstore
    container_name: bookstore_server
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"