version: "2.7"
services:
  database:
    image: postgres
    container_name: bookstore_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    # if you need to hide env vars:
    #env_file:
    #    - .env
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

  server:
    build: ./
    command: ./bookstore
    container_name: bookstore_server
    environment:
      POSTGRES_PASSWORD: example
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"